/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Dimension;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import learning.EpsilonGreedy;
import learning.ExperimentData;
import learning.Matrix;
import learning.QLearner;

/** 
 *
 * @author alessandrobisiani
 */
public class MainFrame extends javax.swing.JFrame {

    private static JFrame tempLabelFrame;
    private String[] stateSpace;
    private QLearner qLearner;
    
    
    public MainFrame() {
        initComponents();
        qLearner = new QLearner(qMatrix,rMatrix);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jMenuItem1 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        rMatrix = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        qMatrix = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        matrixSizeTextField = new javax.swing.JTextField();
        episodesJTextField = new javax.swing.JTextField();
        gammaJTextField = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        alphaJTextField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        testButton = new javax.swing.JButton();
        testTextField2 = new javax.swing.JTextField();
        newMatrixButton = new javax.swing.JButton();
        epsilonJTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        runSAJButton = new javax.swing.JButton();
        setSAJButton = new javax.swing.JButton();
        goalStateJTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        initialStateJTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemNew = new javax.swing.JMenuItem();
        jMenuItemOpen = new javax.swing.JMenuItem();
        jMenuItemSave = new javax.swing.JMenuItem();
        jMenuItemExport = new javax.swing.JMenuItem();
        jMenuItemQuit = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jScrollPane1.setBorder(null);

        rMatrix.setModel(new DefaultTableModel(new Object[][] {{"state1",1,2,3,4,5,6,7,8,9},
            {"state2",10,11,12,0,0,0,0,0,0},
            {"state3",0,0,0,0,0,0,0,0,0},
            {"state4",0,0,0,0,0,0,0,0,0},
            {"state5",0,0,0,0,0,0,0,0,0},
            {"state6",0,0,0,0,0,0,0,0,0},
            {"state7",0,0,0,0,0,0,0,0,0},
            {"state8",0,0,0,0,0,0,0,0,0},
            {"state9",0,0,0,0,0,0,0,0,0},
            {"state10",0,0,0,0,0,0,0,0,0}},
        new String[] {"","state1","state2","state3","state4",
            "state5","state6","state7","state8","state9","state10"}));
/*
rMatrix.setModel(new javax.swing.table.DefaultTableModel(

    new Object[][]     {{0,0,0,0},
        {0,0,0,0},
        {0,0,0,0},
        {0,0,0,0}},

    new String[] {"1","2","3","4"}

    ));
    */
    rMatrix.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
    rMatrix.setColumnSelectionAllowed(true);
    jScrollPane1.setViewportView(rMatrix);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 37;
    gridBagConstraints.gridwidth = 16;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.ipadx = 431;
    gridBagConstraints.ipady = 340;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    gridBagConstraints.insets = new java.awt.Insets(6, 12, 0, 0);
    getContentPane().add(jScrollPane1, gridBagConstraints);

    jScrollPane2.setBorder(null);

    qMatrix.setModel(new DefaultTableModel(new Object[][] {{"state1",0,0,0,0,0,0,0,0,0},
        {"state2",0,0,0,0,0,0,0,0,0},
        {"state3",0,0,0,0,0,0,0,0,0},
        {"state4",0,0,0,0,0,0,0,0,0},
        {"state5",0,0,0,0,0,0,0,0,0},
        {"state6",0,0,0,0,0,0,0,0,0},
        {"state7",0,0,0,0,0,0,0,0,0},
        {"state8",0,0,0,0,0,0,0,0,0},
        {"state9",0,0,0,0,0,0,0,0,0},
        {"state10",0,0,0,0,0,0,0,0,0}},
    new String[] {"","state1","state2","state3","state4",
        "state5","state6","state7","state8","state9","state10"})
);
qMatrix.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
qMatrix.setColumnSelectionAllowed(true);
qMatrix.setGridColor(new java.awt.Color(102, 153, 255));
jScrollPane2.setViewportView(qMatrix);

gridBagConstraints = new java.awt.GridBagConstraints();
gridBagConstraints.gridx = 16;
gridBagConstraints.gridy = 37;
gridBagConstraints.gridwidth = 13;
gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
gridBagConstraints.ipadx = 454;
gridBagConstraints.ipady = 340;
gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
gridBagConstraints.weightx = 1.0;
gridBagConstraints.weighty = 1.0;
gridBagConstraints.insets = new java.awt.Insets(6, 28, 0, 15);
getContentPane().add(jScrollPane2, gridBagConstraints);

jLabel1.setText("Reward Matrix");
gridBagConstraints = new java.awt.GridBagConstraints();
gridBagConstraints.gridx = 0;
gridBagConstraints.gridy = 36;
gridBagConstraints.gridwidth = 3;
gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
gridBagConstraints.insets = new java.awt.Insets(12, 12, 0, 0);
getContentPane().add(jLabel1, gridBagConstraints);

jLabel2.setText("Q Matrix");
gridBagConstraints = new java.awt.GridBagConstraints();
gridBagConstraints.gridx = 16;
gridBagConstraints.gridy = 36;
gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
gridBagConstraints.insets = new java.awt.Insets(12, 28, 0, 0);
getContentPane().add(jLabel2, gridBagConstraints);

jLabel4.setText("Episodes");
gridBagConstraints = new java.awt.GridBagConstraints();
gridBagConstraints.gridx = 0;
gridBagConstraints.gridy = 0;
gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
gridBagConstraints.insets = new java.awt.Insets(18, 20, 0, 0);
getContentPane().add(jLabel4, gridBagConstraints);

jLabel5.setText("Learning Rate");
gridBagConstraints = new java.awt.GridBagConstraints();
gridBagConstraints.gridx = 9;
gridBagConstraints.gridy = 5;
gridBagConstraints.gridwidth = 2;
gridBagConstraints.gridheight = 2;
gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
gridBagConstraints.insets = new java.awt.Insets(1, 18, 0, 0);
getContentPane().add(jLabel5, gridBagConstraints);

jLabel6.setText("Discount Factor");
gridBagConstraints = new java.awt.GridBagConstraints();
gridBagConstraints.gridx = 9;
gridBagConstraints.gridy = 0;
gridBagConstraints.gridwidth = 2;
gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
gridBagConstraints.insets = new java.awt.Insets(18, 3, 0, 0);
getContentPane().add(jLabel6, gridBagConstraints);

jLabel7.setText("Policy");
gridBagConstraints = new java.awt.GridBagConstraints();
gridBagConstraints.gridx = 0;
gridBagConstraints.gridy = 5;
gridBagConstraints.gridheight = 2;
gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
gridBagConstraints.insets = new java.awt.Insets(1, 39, 0, 0);
getContentPane().add(jLabel7, gridBagConstraints);

jLabel8.setText("Algorithm");
gridBagConstraints = new java.awt.GridBagConstraints();
gridBagConstraints.gridx = 16;
gridBagConstraints.gridy = 0;
gridBagConstraints.gridwidth = 2;
gridBagConstraints.gridheight = 3;
gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
gridBagConstraints.insets = new java.awt.Insets(29, 36, 0, 0);
getContentPane().add(jLabel8, gridBagConstraints);

matrixSizeTextField.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        matrixSizeTextFieldActionPerformed(evt);
    }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 23;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.gridheight = 5;
    gridBagConstraints.ipadx = 40;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(1, 29, 0, 0);
    getContentPane().add(matrixSizeTextField, gridBagConstraints);

    episodesJTextField.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            episodesJTextFieldActionPerformed(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.gridwidth = 4;
    gridBagConstraints.gridheight = 2;
    gridBagConstraints.ipadx = 73;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(12, 6, 0, 0);
    getContentPane().add(episodesJTextField, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 11;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.gridheight = 2;
    gridBagConstraints.ipadx = 83;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(12, 6, 0, 0);
    getContentPane().add(gammaJTextField, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.gridwidth = 4;
    gridBagConstraints.gridheight = 6;
    gridBagConstraints.ipadx = 73;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(2, 6, 0, 0);
    getContentPane().add(jTextField5, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 11;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.gridheight = 6;
    gridBagConstraints.ipadx = 83;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(2, 6, 0, 0);
    getContentPane().add(alphaJTextField, gridBagConstraints);

    jButton1.setText("Update");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 24;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.gridwidth = 3;
    gridBagConstraints.gridheight = 8;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(2, 6, 0, 0);
    getContentPane().add(jButton1, gridBagConstraints);

    jLabel9.setText("(Limit of 10)");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 27;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 0);
    getContentPane().add(jLabel9, gridBagConstraints);

    jButton3.setText("Run");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 23;
    gridBagConstraints.gridy = 14;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.gridheight = 11;
    gridBagConstraints.ipadx = 64;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(2, 29, 0, 0);
    getContentPane().add(jButton3, gridBagConstraints);

    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Q-Learning", "SARSA"}));
    jComboBox1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jComboBox1ActionPerformed(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 18;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.gridwidth = 4;
    gridBagConstraints.gridheight = 4;
    gridBagConstraints.ipadx = 42;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(25, 12, 0, 0);
    getContentPane().add(jComboBox1, gridBagConstraints);

    testButton.setText("test");
    testButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            testButtonActionPerformed(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 4;
    gridBagConstraints.gridy = 38;
    gridBagConstraints.gridwidth = 5;
    gridBagConstraints.gridheight = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(23, 2, 0, 0);
    getContentPane().add(testButton, gridBagConstraints);

    testTextField2.setText("matrix size");
    testTextField2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            testTextField2ActionPerformed(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 9;
    gridBagConstraints.gridy = 38;
    gridBagConstraints.ipadx = 70;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(22, 6, 0, 0);
    getContentPane().add(testTextField2, gridBagConstraints);

    newMatrixButton.setText("New Matrix");
    newMatrixButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            newMatrixButtonActionPerformed(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 16;
    gridBagConstraints.gridy = 38;
    gridBagConstraints.gridwidth = 3;
    gridBagConstraints.gridheight = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(23, 17, 0, 0);
    getContentPane().add(newMatrixButton, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 14;
    gridBagConstraints.gridwidth = 4;
    gridBagConstraints.gridheight = 11;
    gridBagConstraints.ipadx = 73;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(3, 6, 0, 0);
    getContentPane().add(epsilonJTextField, gridBagConstraints);

    jLabel10.setText("Epsilon");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 23;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(3, 30, 0, 0);
    getContentPane().add(jLabel10, gridBagConstraints);

    jButton4.setText("set test");
    jButton4.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton4ActionPerformed(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 38;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.gridheight = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(23, 6, 0, 0);
    getContentPane().add(jButton4, gridBagConstraints);

    runSAJButton.setText("Run SA");
    runSAJButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            runSAJButtonActionPerformed(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 12;
    gridBagConstraints.gridy = 38;
    gridBagConstraints.gridwidth = 3;
    gridBagConstraints.gridheight = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(23, 6, 0, 0);
    getContentPane().add(runSAJButton, gridBagConstraints);

    setSAJButton.setText("set SA");
    setSAJButton.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            setSAJButtonActionPerformed(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 11;
    gridBagConstraints.gridy = 38;
    gridBagConstraints.gridheight = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(23, 5, 0, 0);
    getContentPane().add(setSAJButton, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 18;
    gridBagConstraints.gridy = 23;
    gridBagConstraints.gridwidth = 5;
    gridBagConstraints.gridheight = 13;
    gridBagConstraints.ipadx = 81;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(6, 12, 0, 0);
    getContentPane().add(goalStateJTextField, gridBagConstraints);

    jLabel12.setText("Goal State");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 16;
    gridBagConstraints.gridy = 23;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.gridheight = 12;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(12, 36, 0, 0);
    getContentPane().add(jLabel12, gridBagConstraints);

    initialStateJTextField.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            initialStateJTextFieldActionPerformed(evt);
        }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 18;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.gridwidth = 4;
    gridBagConstraints.gridheight = 10;
    gridBagConstraints.ipadx = 80;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(6, 12, 0, 0);
    getContentPane().add(initialStateJTextField, gridBagConstraints);

    jLabel13.setText("Initial State");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 16;
    gridBagConstraints.gridy = 5;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.gridheight = 9;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(12, 28, 0, 0);
    getContentPane().add(jLabel13, gridBagConstraints);

    jMenu1.setText("File");

    jMenuItemNew.setText("New");
    jMenuItemNew.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemNewActionPerformed(evt);
        }
    });
    jMenu1.add(jMenuItemNew);

    jMenuItemOpen.setText("Open");
    jMenu1.add(jMenuItemOpen);

    jMenuItemSave.setText("Save");
    jMenuItemSave.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemSaveActionPerformed(evt);
        }
    });
    jMenu1.add(jMenuItemSave);

    jMenuItemExport.setText("Export");
    jMenu1.add(jMenuItemExport);

    jMenuItemQuit.setText("Quit");
    jMenu1.add(jMenuItemQuit);

    jMenuBar1.add(jMenu1);

    setJMenuBar(jMenuBar1);

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemNewActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void testTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testTextField2ActionPerformed
        
    }//GEN-LAST:event_testTextField2ActionPerformed

    private void testButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testButtonActionPerformed
       
            File f = new File(".");
            System.out.println(f.getAbsolutePath());
        
        
        
        
            /*
            qLearner.setTDThreshold(Double.parseDouble(tdThresholdJTextField.getText()));
            qLearner.setPolicy(new EpsilonGreedy(qLearner,Double.parseDouble(epsilonJTextField.getText())));
            qLearner.setAlpha(Double.parseDouble(alphaJTextField.getText()));
            qLearner.setGamma(Double.parseDouble(gammaJTextField.getText()));
            int ep = Integer.parseInt(episodesJTextField.getText());
            for(int i=0;i<ep;i++){
            resetQMatrix();
            qLearner.episode();
            }
            
            System.out.println(rMatrix.getModel().getValueAt(0,0));
            System.out.println(rMatrix.getModel().getValueAt(1,1));
            System.out.println(rMatrix.getModel().getValueAt(2,2));
            Object o = rMatrix.getModel().getValueAt(2,2);
            String s = "";
            int i = 0;
            if(o instanceof Integer){
            i = (Integer)rMatrix.getModel().getValueAt(2,2) + (Integer)rMatrix.getModel().getValueAt(2,2);
            System.out.println(i);
            } else if(o instanceof String){
            s = (String)rMatrix.getModel().getValueAt(2,2) + (String)rMatrix.getModel().getValueAt(2,2);
            System.out.println(s);
            }
            System.out.println(o.getClass());
            */
            
            //rMatrix.setModel(new DefaultTableModel(new Object[][] {{1,2,3},{4,5,6}}, new String[] {"s1","s2","s3"}));
            //System.out.println(qMatrix.getValueAt(0,0));        //Test of whether getValueAt() returns the value displayed by the table which may be arbitrarily modified.
            //System.out.println(qMatrix.getModel().getValueAt(0,0));//Test that the TableModel assoc with the JTable is updated alongside the graphical representation.
            //rMatrix.setModel(new RMatrix());
        
    }//GEN-LAST:event_testButtonActionPerformed

    private void episodesJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_episodesJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_episodesJTextFieldActionPerformed

    private void matrixSizeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matrixSizeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matrixSizeTextFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String text = matrixSizeTextField.getText();
        int mSize = Integer.parseInt(text);
        if(mSize <= 10 && mSize > 1){
            System.out.println(mSize);
        } else {
            final JOptionPane warning = new JOptionPane();
            warning.showMessageDialog(this, "Specify a number between 2 and 10 inclusive");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void newMatrixButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newMatrixButtonActionPerformed
        tempLabelFrame = new JFrame("State Space");
        tempLabelFrame.getContentPane().add(new StateSpacePanel(this));
        tempLabelFrame.pack();
        tempLabelFrame.setVisible(true);
    }//GEN-LAST:event_newMatrixButtonActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        episodesJTextField.setText("10");
        gammaJTextField.setText("0.6");
        alphaJTextField.setText("0.2");
        epsilonJTextField.setText("0.5");
        resetQMatrix();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void runSAJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runSAJButtonActionPerformed
       
        qLearner.setPolicy(new EpsilonGreedy(qLearner,Double.parseDouble(epsilonJTextField.getText())));
        qLearner.setAlpha(Double.parseDouble(alphaJTextField.getText()));
        qLearner.setGamma(Double.parseDouble(gammaJTextField.getText()));
        qLearner.setGoalState(goalStateJTextField.getText());
        qLearner.setInitialState(initialStateJTextField.getText());
        
        qLearner.experiment(Integer.parseInt(episodesJTextField.getText()));
        
        System.out.println(qLearner.getGoalState());
    }//GEN-LAST:event_runSAJButtonActionPerformed

    private void setSAJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setSAJButtonActionPerformed
        episodesJTextField.setText("10");
        gammaJTextField.setText("0.6");
        alphaJTextField.setText("0.2");
        epsilonJTextField.setText("0.35");
        goalStateJTextField.setText("25");
        initialStateJTextField.setText("1");
        setSAExperimentMatrices();
        
    }//GEN-LAST:event_setSAJButtonActionPerformed

    private void initialStateJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_initialStateJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_initialStateJTextFieldActionPerformed

    private void jMenuItemSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSaveActionPerformed
        FileOutputStream out = null;
        FileInputStream in = null;
        try {
            out = new FileOutputStream("testfile.txt");
            ObjectOutputStream objectOut = new ObjectOutputStream(out);
            objectOut.writeObject(qLearner.getExperimentData());
            
            in = new FileInputStream("testfile.txt");
            ObjectInputStream objectIn = new ObjectInputStream(in);
            Object o = objectIn.readObject();
            if(o instanceof ExperimentData){
                System.out.println("shit, it actually sorta works.");
                ExperimentData data = (ExperimentData) o;
                data.printSteps();
            } else {
                System.out.println("try again");
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                out.close();
                in.close();
            } catch (IOException ex) {
                Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jMenuItemSaveActionPerformed
    
    public static void closeLabelFrame(){
        tempLabelFrame.dispose();
    }
    
    //takes the states input as an ArrayList and calls the R and Q matrix constructors, discarding the old matrices and setting the new ones to be visible.
    public void createMatrices(ArrayList<String> statesList){
        int s = statesList.size();
        String[] states = new String[s];
        for(int i=0 ; i<s ; i++){
            states[i] = statesList.get(i);
            System.out.println(states[i] + " THESE ARE THE DROIDS YOU'RE LOOKING FOR - " + i);
        }
        
        
        MainFrame.closeLabelFrame();
        resetMatrices(qMatrix, rMatrix, states);
    }
    
    public boolean resetMatrices(JTable qMatrix, JTable rMatrix, String[] states){
        int c = 0;
        int r = 0;
        boolean b = false;
        //creates String[] beginning with null value followed by states input to the method.
        int l = states.length;
        String [] statesList = new String[l+1];
        statesList[0] = "";
        for(int i=1 ; i<=l ; i++){
            statesList[i] = states[i-1];
        }
        //populates the Q matrix with zeros and row headers.
        String[][] qmatrix = new String[l][l+1];
        for(int i=0 ; i<l ; i++){
            for(int j=0 ; j<=l ; j++){
                if(j==0){
                    qmatrix[i][0] = states[i];
                    r++;
                } else {
                    qmatrix[i][j] = "0";
                    c++;
                } 
            }
        }
        //populates R matrix w/ row headers only
        String[][] rmatrix = new String[l][l+1];
        for(int i=0 ; i<l ; i++){
            for(int j=0 ; j<=l ; j++){
                if(j==0){
                    rmatrix[i][0] = states[i];
                    r++;
                } else {
                    rmatrix[i][j] = "";
                    c++;
                } 
            }
        }
        
        //Create new DefaultTableModel s, set them as models for Q and R matrices and as designated TableModels in qLearner.
        //The purpose of this is to make sure there's a reference to DefaultTableModel objects due to their great methods.
        Matrix qModel = new Matrix(qmatrix, statesList);
        Matrix rModel = new Matrix(rmatrix, statesList);
        qMatrix.setModel(qModel);
        rMatrix.setModel(rModel);
        rMatrix.setPreferredScrollableViewportSize(new Dimension(400,400));
        qMatrix.setPreferredScrollableViewportSize(new Dimension(400,400));
        
        //jScrollPane1.createHorizontalScrollBar();
        //jScrollPane2.createHorizontalScrollBar();
        
        //Resize events trigger an evaluation of whether to use AUTO_RESIZE or not. 
        //The result is he table fills the JScrollPane until it won't fit, then assumes the preferred size and creates a scroll bar.
        rMatrix.getParent().addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(final ComponentEvent e) {
                if (rMatrix.getPreferredSize().width < rMatrix.getParent().getWidth()) {
                    rMatrix.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
                } else {
                    rMatrix.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
                }
            }
        });
        qMatrix.getParent().addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(final ComponentEvent e) {
                if (qMatrix.getPreferredSize().width < qMatrix.getParent().getWidth()) {
                    qMatrix.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
                } else {
                    qMatrix.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
                }
            }
        });
        
        //When first creating the matrices also evaluate whether either should use AUTO_RESIZE.
        if (qMatrix.getPreferredSize().width < qMatrix.getParent().getWidth()) {
                    qMatrix.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
                } else {
                    qMatrix.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
                }
        if (rMatrix.getPreferredSize().width < rMatrix.getParent().getWidth()) {
                    rMatrix.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
                } else {
                    rMatrix.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
                }
        
        for(int y=0 ; y<=l ; y++){
                rMatrix.getColumnModel().getColumn(y).setMinWidth(40);
                rMatrix.getColumnModel().getColumn(y).setPreferredWidth(40);
                qMatrix.getColumnModel().getColumn(y).setMinWidth(40);
                qMatrix.getColumnModel().getColumn(y).setPreferredWidth(40);
        }
        
        qLearner.setModels(qModel, rModel);
        stateSpace = states;
        //qLearner.resetStartingPosition();
        System.out.println("Matrices reset");
        if((c/l)==r){
            b=true;
        }
        return b;
    }
    
    public void resetQMatrix(){
        String[] states = stateSpace;
        int l = states.length;
        TableModel tm = qMatrix.getModel();
        //String[][] qmatrix = new String[l][l+1];
        for(int i=0 ; i<l ; i++){
            for(int j=0 ; j<=l ; j++){
                if(j==0){
                    tm.setValueAt(states[i], i, 0);
                } else {
                    tm.setValueAt("0", i, j);
                } 
            }
        }
        qMatrix.repaint();
    }
    
    public void setSAExperimentMatrices(){
        resetQMatrix();
        TableModel model = rMatrix.getModel();
        model.setValueAt("0", 0, 1);
        model.setValueAt("0", 1, 1);
        model.setValueAt("0", 5, 1);
        model.setValueAt("0", 0, 2);
        model.setValueAt("0", 1, 2);
        model.setValueAt("0", 2, 2);
        model.setValueAt("0", 6, 2);
        model.setValueAt("0", 1, 3);
        model.setValueAt("0", 2, 3);
        model.setValueAt("0", 3, 3);
        model.setValueAt("0", 7, 3);
        model.setValueAt("0", 2, 4);
        model.setValueAt("0", 3, 4);
        model.setValueAt("0", 4, 4);
        model.setValueAt("0", 8, 4);
        model.setValueAt("0", 3, 5);
        model.setValueAt("0", 4, 5);
        model.setValueAt("0", 9, 5);
        model.setValueAt("0", 0, 6);
        model.setValueAt("0", 5, 6);
        model.setValueAt("0", 6, 6);
        model.setValueAt("0", 10, 6);
        model.setValueAt("-100", 1, 7);
        model.setValueAt("-100", 5, 7);
        model.setValueAt("-100", 6, 7);
        model.setValueAt("-100", 7, 7);
        model.setValueAt("-100", 11, 7);
        model.setValueAt("0", 2, 8);
        model.setValueAt("0", 6, 8);
        model.setValueAt("0", 7, 8);
        model.setValueAt("0", 8, 8);
        model.setValueAt("0", 12, 8);
        model.setValueAt("-100", 7, 9);
        model.setValueAt("-100", 8, 9);
        model.setValueAt("-100", 9, 9);
        model.setValueAt("-100", 3, 9);
        model.setValueAt("-100", 13, 9);
        model.setValueAt("0", 4, 10);
        model.setValueAt("0", 8, 10);
        model.setValueAt("0", 9, 10);
        model.setValueAt("0", 14, 10);
        model.setValueAt("-100", 5, 11);
        model.setValueAt("-100", 10, 11);
        model.setValueAt("-100", 11, 11);
        model.setValueAt("-100", 15, 11);
        model.setValueAt("0", 6, 12);
        model.setValueAt("0", 10, 12);
        model.setValueAt("0", 11, 12);
        model.setValueAt("0", 12, 12);
        model.setValueAt("0", 16, 12);
        model.setValueAt("0", 7, 13);
        model.setValueAt("0", 11, 13);
        model.setValueAt("0", 12, 13);
        model.setValueAt("0", 13, 13);
        model.setValueAt("0", 17, 13);
        model.setValueAt("0", 8, 14);
        model.setValueAt("0", 12, 14);
        model.setValueAt("0", 13, 14);
        model.setValueAt("0", 14, 14);
        model.setValueAt("0", 18, 14);
        model.setValueAt("0", 9, 15);
        model.setValueAt("0", 13, 15);
        model.setValueAt("0", 14, 15);
        model.setValueAt("0", 19, 15);
        model.setValueAt("0", 10, 16);
        model.setValueAt("0", 15, 16);
        model.setValueAt("0", 16, 16);
        model.setValueAt("0", 20, 16);
        
        model.setValueAt("0", 11, 17);
        model.setValueAt("0", 15, 17);
        model.setValueAt("0", 16, 17);
        model.setValueAt("0", 17, 17);
        model.setValueAt("0", 21, 17);
        model.setValueAt("-100", 12, 18);
        model.setValueAt("-100", 16, 18);
        model.setValueAt("-100", 17, 18);
        model.setValueAt("-100", 18, 18);
        model.setValueAt("-100", 22, 18);
        model.setValueAt("0", 13, 19);
        model.setValueAt("0", 17, 19);
        model.setValueAt("0", 18, 19);
        model.setValueAt("0", 19, 19);
        model.setValueAt("0", 23, 19);
        model.setValueAt("-100", 14, 20);
        model.setValueAt("-100", 18, 20);
        model.setValueAt("-100", 19, 20);
        model.setValueAt("-100", 24, 20);
        model.setValueAt("0", 15, 21);
        model.setValueAt("0", 20, 21);
        model.setValueAt("0", 21, 21);
        model.setValueAt("0", 16, 22);
        model.setValueAt("0", 20, 22);
        model.setValueAt("0", 21, 22);
        model.setValueAt("0", 22, 22);
        model.setValueAt("0", 17, 23);
        model.setValueAt("0", 21, 23);
        model.setValueAt("0", 22, 23);
        model.setValueAt("0", 23, 23);
        model.setValueAt("0", 18, 24);
        model.setValueAt("0", 22, 24);
        model.setValueAt("0", 23, 24);
        model.setValueAt("0", 24, 24);
        model.setValueAt("100", 19, 25);
        model.setValueAt("100", 23, 25);
        model.setValueAt("100", 24, 25);
        /*model.setValueAt("0", 0, 1);
        model.setValueAt("0", 1, 1);
        model.setValueAt("0", 5, 1);
        model.setValueAt("0", 0, 2);
        model.setValueAt("0", 1, 2);
        model.setValueAt("0", 2, 2);
        model.setValueAt("0", 6, 2);
        model.setValueAt("0", 1, 3);
        model.setValueAt("0", 2, 3);
        model.setValueAt("0", 3, 3);
        model.setValueAt("0", 7, 3);
        model.setValueAt("0", 2, 4);
        model.setValueAt("0", 3, 4);
        model.setValueAt("0", 4, 4);
        model.setValueAt("0", 8, 4);
        model.setValueAt("0", 3, 5);
        model.setValueAt("0", 4, 5);
        model.setValueAt("0", 9, 5);
        model.setValueAt("0", 0, 6);
        model.setValueAt("0", 5, 6);
        model.setValueAt("0", 6, 6);
        model.setValueAt("-50", 1, 7);
        model.setValueAt("-50", 5, 7);
        model.setValueAt("-50", 6, 7);
        model.setValueAt("-50", 7, 7);
        model.setValueAt("-50", 10, 7);
        model.setValueAt("0", 2, 8);
        model.setValueAt("0", 6, 8);
        model.setValueAt("0", 7, 8);
        model.setValueAt("0", 8, 8);
        model.setValueAt("0", 11, 8);
        model.setValueAt("0", 3, 9);
        model.setValueAt("0", 7, 9);
        model.setValueAt("0", 8, 9);
        model.setValueAt("0", 9, 9);
        model.setValueAt("0", 12, 9);
        model.setValueAt("0", 4, 10);
        model.setValueAt("0", 8, 10);
        model.setValueAt("0", 9, 10);
        model.setValueAt("0", 13, 10);
        model.setValueAt("0", 6, 11);
        model.setValueAt("0", 10, 11);
        model.setValueAt("0", 11, 11);
        model.setValueAt("0", 15, 11);
        model.setValueAt("0", 7, 12);
        model.setValueAt("0", 10, 12);
        model.setValueAt("0", 11, 12);
        model.setValueAt("0", 12, 12);
        model.setValueAt("0", 16, 12);
        model.setValueAt("0", 8, 13);
        model.setValueAt("0", 11, 13);
        model.setValueAt("0", 12, 13);
        model.setValueAt("0", 13, 13);
        model.setValueAt("0", 9, 14);
        model.setValueAt("0", 12, 14);
        model.setValueAt("0", 13, 14);
        model.setValueAt("0", 14, 15);
        model.setValueAt("0", 15, 15);
        model.setValueAt("0", 17, 15);
        model.setValueAt("0", 10, 16);
        model.setValueAt("0", 14, 16);
        model.setValueAt("0", 15, 16);
        model.setValueAt("0", 16, 16);
        model.setValueAt("0", 18, 16);
        model.setValueAt("-100", 11, 17);
        model.setValueAt("-100", 15, 17);
        model.setValueAt("-100", 16, 17);
        model.setValueAt("-100", 19, 17);
        model.setValueAt("0", 14, 18);
        model.setValueAt("0", 17, 18);
        model.setValueAt("0", 18, 18);
        model.setValueAt("0", 15, 19);
        model.setValueAt("0", 17, 19);
        model.setValueAt("0", 18, 19);
        model.setValueAt("0", 19, 19);
        model.setValueAt("0", 16, 20);
        model.setValueAt("0", 18, 20);
        model.setValueAt("0", 19, 20);
        model.setValueAt("0", 20, 20);
        model.setValueAt("0", 19, 21);
        model.setValueAt("0", 20, 21);
        model.setValueAt("0", 21, 21);
        model.setValueAt("100", 20, 22);
        model.setValueAt("100", 21, 22);
        */
        rMatrix.repaint();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alphaJTextField;
    private javax.swing.JTextField episodesJTextField;
    private javax.swing.JTextField epsilonJTextField;
    private javax.swing.JTextField gammaJTextField;
    private javax.swing.JTextField goalStateJTextField;
    private javax.swing.JTextField initialStateJTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemExport;
    private javax.swing.JMenuItem jMenuItemNew;
    private javax.swing.JMenuItem jMenuItemOpen;
    private javax.swing.JMenuItem jMenuItemQuit;
    private javax.swing.JMenuItem jMenuItemSave;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField matrixSizeTextField;
    private javax.swing.JButton newMatrixButton;
    private javax.swing.JTable qMatrix;
    private javax.swing.JTable rMatrix;
    private javax.swing.JButton runSAJButton;
    private javax.swing.JButton setSAJButton;
    private javax.swing.JButton testButton;
    private javax.swing.JTextField testTextField2;
    // End of variables declaration//GEN-END:variables
}
