/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JFrame;

/**
 *
 * @author alessandrobisiani
 */
public class StateSpacePanel extends javax.swing.JPanel{

    private ArrayList<String> listOfStates = new ArrayList<String>();
    //static String stringListOfStates;
    private MainFrame mainFrame;
    
    /**
     *@param mFrame    The MainFrame instance that created the StateSpacePanel instance
     */
    public StateSpacePanel(MainFrame mFrame) {
        initComponents();
        mainFrame = mFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        stateSpace = new javax.swing.JTextArea();
        createJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        stateSpace.setColumns(20);
        stateSpace.setRows(5);
        stateSpace.setText("1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25");
        jScrollPane1.setViewportView(stateSpace);

        createJButton.setText("Create");
        createJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createJButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Enter the desired states below, separated by a space.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 464, Short.MAX_VALUE)
                        .addComponent(createJButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(createJButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    //Harvest JTextArea input and enter each state name in an ArrayList<String> for use.
    //The states entered should be divided by a space.
    private void createJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createJButtonActionPerformed
        listOfStates.clear();
        String states = stateSpace.getText();
        String word = "";
        int lengthOfStates = states.length();
        //CharSequence sepChar = System.getProperty("line.separator");
        
        for(int i=0; i<lengthOfStates; i++){
            
            if(i==lengthOfStates-1 && states.charAt(i)==' '){
                listOfStates.add(word);
            } else if(i==lengthOfStates-1){
                word = word + states.charAt(i);
                listOfStates.add(word);
            } else if(states.charAt(i) ==' '){
                listOfStates.add(word);
                System.out.println(word);                //A test to check whether the loop cycles through each word
                word = "";
            } else {
                word = word + states.charAt(i);
            }
        }
        
        //Tests of the state of the fields after harvesting the information from JTextArea
        System.out.println(states);
        System.out.println(states.length());
        System.out.println(listOfStates);
        mainFrame.data.resetData();
        //Create the matrices using static method and ArrayList<String> containing the state names. This method also calls dispose() on the instance of StateSpacePanel.
        mainFrame.createMatrices(listOfStates);
             
    }//GEN-LAST:event_createJButtonActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea stateSpace;
    // End of variables declaration//GEN-END:variables

    
}
